/** @format */

export const data = [
  {
    id: 1,
    first_name: 'Geoffrey',
    last_name: 'Harnwell',
    email: 'gharnwell0@imdb.com',
    gender: 'Male',
    date_of_birth: '2005-02-11T18:00:08Z',
  },
  {
    id: 2,
    first_name: 'Lonnard',
    last_name: 'Senechell',
    email: 'lsenechell1@about.com',
    gender: 'Male',
    date_of_birth: '2011-11-26T09:27:25Z',
  },
  {
    id: 3,
    first_name: 'Dasya',
    last_name: 'Faas',
    email: 'dfaas2@zdnet.com',
    gender: 'Female',
    date_of_birth: '2003-04-16T21:30:21Z',
  },
  {
    id: 4,
    first_name: 'Fons',
    last_name: 'Dallinder',
    email: 'fdallinder3@canalblog.com',
    gender: 'Polygender',
    date_of_birth: '2002-04-19T21:47:50Z',
  },
  {
    id: 5,
    first_name: 'Mart',
    last_name: 'Kinneir',
    email: 'mkinneir4@buzzfeed.com',
    gender: 'Male',
    date_of_birth: '2003-09-08T21:58:27Z',
  },
  {
    id: 6,
    first_name: 'Lynnett',
    last_name: 'Roughley',
    email: 'lroughley5@cnn.com',
    gender: 'Female',
    date_of_birth: '2002-12-31T02:21:44Z',
  },
  {
    id: 7,
    first_name: 'Austin',
    last_name: 'Binnie',
    email: 'abinnie6@youtu.be',
    gender: 'Male',
    date_of_birth: '2001-02-22T03:51:06Z',
  },
  {
    id: 8,
    first_name: 'Teriann',
    last_name: 'Jellett',
    email: 'tjellett7@networksolutions.com',
    gender: 'Female',
    date_of_birth: '2007-07-28T12:58:22Z',
  },
  {
    id: 9,
    first_name: 'Briggs',
    last_name: 'Rake',
    email: 'brake8@alibaba.com',
    gender: 'Male',
    date_of_birth: '2013-03-10T10:46:13Z',
  },
  {
    id: 10,
    first_name: 'Wilfrid',
    last_name: 'Fincham',
    email: 'wfincham9@canalblog.com',
    gender: 'Male',
    date_of_birth: '2003-12-29T18:49:21Z',
  },
  {
    id: 11,
    first_name: 'Alain',
    last_name: 'Caldecott',
    email: 'acaldecotta@youtu.be',
    gender: 'Genderfluid',
    date_of_birth: '2018-07-07T20:34:36Z',
  },
  {
    id: 12,
    first_name: 'Malia',
    last_name: 'Bedenham',
    email: 'mbedenhamb@mtv.com',
    gender: 'Female',
    date_of_birth: '2012-08-09T12:03:55Z',
  },
  {
    id: 13,
    first_name: 'Wallace',
    last_name: 'Zielinski',
    email: 'wzielinskic@bloglovin.com',
    gender: 'Male',
    date_of_birth: '2002-10-04T10:56:54Z',
  },
  {
    id: 14,
    first_name: 'Evonne',
    last_name: 'Jeromson',
    email: 'ejeromsond@miitbeian.gov.cn',
    gender: 'Female',
    date_of_birth: '2007-06-17T02:22:38Z',
  },
  {
    id: 15,
    first_name: 'Pauletta',
    last_name: 'Menauteau',
    email: 'pmenauteaue@spiegel.de',
    gender: 'Female',
    date_of_birth: '2008-02-24T19:14:49Z',
  },
  {
    id: 16,
    first_name: 'Eb',
    last_name: 'Jaime',
    email: 'ejaimef@symantec.com',
    gender: 'Male',
    date_of_birth: '2010-12-01T18:54:53Z',
  },
  {
    id: 17,
    first_name: 'Kaile',
    last_name: 'MacCoveney',
    email: 'kmaccoveneyg@dailymail.co.uk',
    gender: 'Female',
    date_of_birth: '2001-12-25T00:47:18Z',
  },
  {
    id: 18,
    first_name: 'Becka',
    last_name: 'Vasler',
    email: 'bvaslerh@hao123.com',
    gender: 'Female',
    date_of_birth: '2008-10-27T03:13:41Z',
  },
  {
    id: 19,
    first_name: 'Lazare',
    last_name: 'Scemp',
    email: 'lscempi@bing.com',
    gender: 'Male',
    date_of_birth: '2011-07-20T01:33:37Z',
  },
  {
    id: 20,
    first_name: 'Madonna',
    last_name: 'Allewell',
    email: 'mallewellj@last.fm',
    gender: 'Bigender',
    date_of_birth: '2009-12-13T16:14:03Z',
  },
];
